const breadlistbase = {"Basic": {"ingredients": ["Flour (APF)", "Salt", "Water", "Levain"],
                                "measurements": [500, 11, 350, 50],
                                "notes": "Bake Basic",
                                "usernotes": "User Bake Basic"},
                      "40% WW": {"ingredients": ["Flour (APF)", "Flour (WW)", "Salt", "Water", "Levain"],
                                "measurements": [300, 200, 11, 350, 50],
                                "notes": "Bake",
                                "usernotes": "Bake 2.0"},
                      "25% WW + Flax": {"ingredients": ["Flour (APF)", "Flour (WW)", "Roasted Flax Seeds", "Salt", "Water", "Levain"],
                                "measurements": [300, 100, 50, 9, 355, 40],
                                "notes": "Bake",
                                "usernotes": "Bake 2.0"},
                      "25% WW + Flax + Poppy": {"ingredients": ["Flour (APF)", "Flour (WW)", "Roasted Flax Seeds", "Poppy Seeds", "Salt", "Water", "Levain"],
                                "measurements": [300, 100, 20, 20, 9, 355, 40],
                                "notes": "Bake",
                                "usernotes": "Bake 2.0"},
                      "25% WW + Steel Cut Oats": {"ingredients": ["Flour (APF)", "Flour (WW)", "Steel Cut Oats", "Salt", "Water", "Levain"],
                                "measurements": [300, 100, 80, 9, 350, 40],
                                "notes": "Bake",
                                "usernotes": "Bake 2.0"},
                      "Molasses": {"ingredients": ["Flour (APF)", "Salt", "Water", "Levain", "Molasses"],
                                "measurements": [300, 8, 170, 60, 80],
                                "notes": "Bake",
                                "usernotes": "Bake 2.0"},
                      "Chocolate": {"ingredients": ["Flour (APF)", "Cocoa Powder", "Salt", "Brown Sugar", "Water", "Levain"],
                                "measurements": [300, 30, 10, 40, 260, 52],
                                "notes": "Bake Chocolate",
                                "usernotes": "User Bake Chocolate"},
                      "25% WW + Steel Cut Oats + Black Sesame": {"ingredients": ["Flour (APF)", "Flour (WW)", "Steel Cut Oats", "Black Sesame Seeds", "Salt", "Water", "Levain"],
                                "measurements": [300, 100, 60, 20, 10, 340, 40],
                                "notes": "Bake",
                                "usernotes": "Bake 2.0"},
                      "Hot Cross Bun": {"ingredients": ["Flour (APF)", "Salt", "Spices", "Brown Sugar", "Golden Raisins", "Dehydrated Zest Strips", "Water", "Levain"],
                                "measurements": [300, 8, 4, 30, 70, 25, 220, 60],
                                "notes": "Bake",
                                "usernotes": "Bake 2.0"},
                      "Cobber Granary": {"ingredients": ["Flour (Cobber)", "Flour (APF/BF)", "Salt", "Water", "Levain"],
                                "measurements": [200, 100, 7, 210, 30],
                                "notes": "Bake",
                                "usernotes": "Bake 2.0"},
                      "KAF Harvest Grains": {"ingredients": ["Flour (APF)", "Whole Wheat", "KAF Harvest Grains", "Salt", "Water", "Levain"],
                                "measurements": [225, 75, 50, 8, 260, 35],
                                "notes": "Bake",
                                "usernotes": "Bake 2.0"}};

export {breadlistbase};
